version: '3.9'
services:
  pihole:
    image: pihole/pihole:2023.05.2@sha256:8bc45afe1625487aef62859a5bf02f3d7b3429e480f4e29e4689635ab86ec312
    hostname: pihole
    container_name: pihole__pihole
    restart: unless-stopped

    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: 'password'

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    expose:
      - 80

    volumes:
      - type: volume
        source: pihole_data
        target: /etc/pihole

      - type: volume
        source: dnsmasq_data
        target: /etc/dnsmasq.d

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  nginx:
    image: nginx:1.25.2@sha256:25668ef2e4be5c3753148ffe583e2c58c27019582fbd061f2d082839746a5cfa
    hostname: nginx
    container_name: pihole__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default


  cloudflared:
    image: cloudflare/cloudflared:2023.8.2@sha256:93561dfa0032006354be56476f09e3d8743d53d202368672c2847c1631f7be50
    hostname: cloudflared
    container_name: pihole__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - pihole__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  dnsmasq_data:
    name: pihole__dnsmasq_data

  pihole_data:
    name: pihole__pihole_data

networks:
  default:
    name: pihole__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
