version: '3.9'
services:
  pihole:
    image: pihole/pihole:2023.05.2@sha256:06790d4a2409ef65bd2415e0422deb3a242119a43e33f4c9e8b97ca586017743
    hostname: pihole
    container_name: pihole__pihole
    restart: unless-stopped

    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: 'password'

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    expose:
      - 80

    volumes:
      - type: volume
        source: pihole_data
        target: /etc/pihole

      - type: volume
        source: dnsmasq_data
        target: /etc/dnsmasq.d

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  nginx:
    image: nginx:1.25.2@sha256:48a84a0728cab8ac558f48796f901f6d31d287101bc8b317683678125e0d2d35
    hostname: nginx
    container_name: pihole__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default


  cloudflared:
    image: cloudflare/cloudflared:2023.8.1@sha256:797301e9902e88f3df383d28e2b83f39b58703378bff5ffdb0c61c820f617dcc
    hostname: cloudflared
    container_name: pihole__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - pihole__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  dnsmasq_data:
    name: pihole__dnsmasq_data

  pihole_data:
    name: pihole__pihole_data

networks:
  default:
    name: pihole__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
