version: '3.9'
services:
  pihole:
    image: pihole/pihole:2023.11.0@sha256:24b1ef8f66d810faffefdb9b66850bbe2d55013506b892605acef414e210edeb
    hostname: pihole
    container_name: pihole__pihole
    restart: unless-stopped

    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: 'password'

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    expose:
      - 80

    volumes:
      - type: volume
        source: pihole_data
        target: /etc/pihole

      - type: volume
        source: dnsmasq_data
        target: /etc/dnsmasq.d

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  nginx:
    image: nginx:1.25.3@sha256:2bdc49f2f8ae8d8dc50ed00f2ee56d00385c6f8bc8a8b320d0a294d9e3b49026
    hostname: nginx
    container_name: pihole__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default


  cloudflared:
    image: cloudflare/cloudflared:2024.1.2@sha256:116171d734c606a7d67f86f6309b56193095e19fd3af478e83fee3f24d93c692
    hostname: cloudflared
    container_name: pihole__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - pihole__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  dnsmasq_data:
    name: pihole__dnsmasq_data

  pihole_data:
    name: pihole__pihole_data

networks:
  default:
    name: pihole__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
